kind: pipeline
name: layouts-api

steps:
  - name: layouts-api-test
    pull: if-not-exists
    image: python:3.7
    commands:
      - pip install invoke
      - inv install
      - inv check
      - inv test