# Generated by Django 3.1.2 on 2020-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='cards',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cards',
            name='comment',
            field=models.CharField(default='No comment', max_length=350),
        ),
        migrations.AddField(
            model_name='cards',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cards',
            name='date',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
