# Generated by Django 3.1.2 on 2020-10-31 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cards",
            name="city_id",
        ),
        migrations.RemoveField(
            model_name="cards",
            name="user_id",
        ),
        migrations.AddField(
            model_name="cards",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.cities"
            ),
        ),
        migrations.AddField(
            model_name="cards",
            name="comment",
            field=models.CharField(default="No comment", max_length=350),
        ),
        migrations.AddField(
            model_name="cards",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cards",
            name="date",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="cards",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SubCards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_link", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=1)),
                ("comment", models.CharField(default="No comment", max_length=350)),
                ("date", models.CharField(default="0", max_length=255)),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.cards",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.cities",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
