# Generated by Django 3.1.2 on 2020-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20201031_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="tel_number",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="subcards",
            name="tel_number",
            field=models.CharField(default="0", max_length=255),
        ),
    ]
